export const JARGON_ES: string[] = [
	'sinergia',
	'holístico',
	'empoderar',
	'potenciar',
	'robusto',
	'escalable',
	'disruptivo',
	'innovador',
	'vanguardia',
	'vanguardista',
	'ecosistema',
	'inmersivo',
	'transformar',
	'revolucionar',
	'optimizar',
	'maximizar',
	'capitalizar',
	'materializar',
	'encarnar',
	'adentrarse',
	'sumergirse',
	'profundizar',
	'abordar',
	'navegar',
	'desbloquear',
	'desentrañar',
	'forjar',
	'tejer',
	'trazar',
	'plasmar',
	'en constante evolución',
	'cambio de paradigma',
	'a medida',
	'próxima generación',
	'de vanguardia',
	'líder en el sector',
	'tecnología puntera',
	'solución integral',
	'alineación estratégica',
	'mejor en su clase',
	'hoja de ruta',
	'propuesta de valor',
	'partes interesadas',
	'misión crítica',
	'a prueba de futuro',
	'en un mundo cada vez más',
	'en la era digital',
	'sin fricciones',
	'escalabilidad',
	'intuitivo',
	'redefinir',
	'apalancar',
	'aprovechar al máximo',
	'fluidez',
	'valor añadido',
	'ventaja competitiva',
	'alinear esfuerzos',
	'eficiencia operativa',
	'impacto transformador',
	'encomiable',
	'invaluable',
	'vibrante',
	'transformador',
	'meticuloso',
	'crucial',
	'fomentar',
	'subrayar',
	'pionero',
	'panorama',
	'crisol',
	'allanar el camino',
	'un sinfín de',
	'una amplia gama de',
	'una gran variedad de',
	'innumerables',
	'huella imborrable',
	'papel fundamental',
	'papel crucial',
	'punto de inflexión',
	'sentar las bases',
	'poner de relieve',
	'se erige como',
	'un testimonio de',
	'da testimonio de',
	'en el ámbito de',
	'perdurable',
	'legado duradero',
	'alineado con',
	'alineada con',
	'en línea con',
	'punto focal',
	'profundamente arraigado',
	'profundamente arraigada',
	'generó debate',
	'generó discusión',
	'presencia activa en redes sociales',
	'presencia activa en redes',
	'en el corazón de',
	'belleza natural',
	'compromiso con',
	'ejemplifica',
	'marca un',
	'representa un',
	'ofrece una mirada',
	'ofrece un vistazo',
	'innovadora',
	'innovadores',
	'innovadoras',
	'robusta',
	'robustos',
	'robustas',
	'escalables',
	'disruptiva',
	'disruptivos',
	'disruptivas',
	'disrupción',
	'inmersiva',
	'inmersivas',
	'transformadora',
	'transformadoras',
	'transformadores',
	'vibrantes',
	'meticulosa',
	'meticulosamente',
	'intuitiva',
	'pionera',
	'pioneros',
	'pioneras',
	'holística',
	'holísticos',
	'holísticas',
	'versátil',
	'versátiles',
	'multifacético',
	'multifacética',
	'polifacético',
	'polifacética',
	'sin precedentes',
	'de talla mundial',
	'centrado en el usuario',
	'centrada en el usuario',
	'centrado en el cliente',
	'basado en datos',
	'basada en datos',
	'impulsado por datos',
	'impulsada por datos',
	'impulsado por la inteligencia artificial',
	'potenciado por ia',
	'de última generación',
	'perfectamente integrado',
	'perfectamente integrada',
	'hiperpersonalizado',
	'hiperpersonalizada',
	'omnicanal',
	'transversal',
	'transversales',
	'agilizar',
	'catalizar',
	'catalizador',
	'reinventar',
	'reimaginar',
	'revolucionario',
	'revolucionaria',
	'revolucionarios',
	'revolucionarias',
	'puntero',
	'punteros',
	'punteras',
	'líder del mercado',
	'referente en el sector',
	'joya escondida',
	'joya oculta',
	'incomparable',
	'inigualable',
	'rico patrimonio',
	'rica historia',
	'rica herencia cultural',
	'enclavado',
	'enclavada',
	'ubicado en el corazón',
	'telón de fondo',
	'abanico de posibilidades',
	'sinónimo de',
	'no es una excepción',
	'no es la excepción',
	'sumérgete',
	'sumergite',
	'potenciá',
	'transformá',
	'desbloqueá',
	'aprovechá al máximo',
	'potenciador',
	'valor agregado',
	'punta de lanza',
	'retorno de inversión',
	'ventajas competitivas',
	'buenas prácticas',
	'mejores prácticas',
	'estado del arte',
	'de extremo a extremo',
	'llave en mano',
	'círculo virtuoso',
	'generar valor',
	'aportar valor',
	'soluciones a medida',
	'ecosistemas',
	'sinergias',
	'paisajes impresionantes',
	'pintoresco',
	'pintoresca',
	'majestuoso',
	'majestuosa',
	'icónico',
	'icónica',
	'emblemático',
	'emblemática',
	'cautivador',
	'cautivadora',
	'deslumbrante',
	'inquebrantable',
	'compromiso inquebrantable',
	'firme compromiso',
	'en constante crecimiento',
	'panorama actual',
	'panorama digital',
	'tapiz',
	'rico tapiz',
	'amalgama',
	'entramado',
	'epítome',
	'buque insignia',
	'de manera fluida',
	'de forma fluida'
];
