export const JARGON_ES: string[] = [
	'sinergia',
	'holístico',
	'empoderar',
	'potenciar',
	'robusto',
	'escalable',
	'disruptivo',
	'innovador',
	'vanguardia',
	'vanguardista',
	'ecosistema',
	'inmersivo',
	'transformar',
	'revolucionar',
	'optimizar',
	'maximizar',
	'capitalizar',
	'materializar',
	'encarnar',
	'adentrarse',
	'sumergirse',
	'profundizar',
	'abordar',
	'navegar',
	'desbloquear',
	'desentrañar',
	'forjar',
	'tejer',
	'trazar',
	'plasmar',
	'en constante evolución',
	'cambio de paradigma',
	'a medida',
	'próxima generación',
	'de vanguardia',
	'líder en el sector',
	'tecnología puntera',
	'solución integral',
	'alineación estratégica',
	'mejor en su clase',
	'hoja de ruta',
	'propuesta de valor',
	'partes interesadas',
	'misión crítica',
	'a prueba de futuro',
	'en un mundo cada vez más',
	'en la era digital',
	'sin fricciones',
	'escalabilidad',
	'intuitivo',
	'redefinir',
	'apalancar',
	'aprovechar al máximo',
	'fluidez',
	'valor añadido',
	'ventaja competitiva',
	'alinear esfuerzos',
	'eficiencia operativa',
	'impacto transformador',
	'encomiable',
	'invaluable',
	'vibrante',
	'transformador',
	'meticuloso',
	'crucial',
	'fomentar',
	'subrayar',
	'pionero',
	'panorama',
	'crisol',
	'allanar el camino',
	'un sinfín de',
	'una amplia gama de',
	'una gran variedad de',
	'innumerables',
	'huella imborrable',
	'papel fundamental',
	'papel crucial',
	'punto de inflexión',
	'sentar las bases',
	'poner de relieve',
	'se erige como',
	'un testimonio de',
	'da testimonio de',
	'en el ámbito de',
	'perdurable',
	'legado duradero',
	'alineado con',
	'alineada con',
	'en línea con',
	'punto focal',
	'profundamente arraigado',
	'profundamente arraigada',
	'generó debate',
	'generó discusión',
	'presencia activa en redes sociales',
	'presencia activa en redes',
	'en el corazón de',
	'belleza natural',
	'compromiso con',
	'ejemplifica',
	'marca un',
	'representa un',
	'ofrece una mirada',
	'ofrece un vistazo'
];
