export const JARGON_EN: string[] = [
	'delve',
	'meticulous',
	'elevate',
	'revolutionize',
	'holistic',
	'empower',
	'realm',
	'seamless',
	'enhance',
	'reinvent',
	'fast-paced',
	'embark',
	'reimagined',
	'game-changer',
	'enable',
	'redefine',
	'adorned',
	'vast',
	'effortlessly',
	'seamlessly',
	'transform',
	'synergy',
	'frictionless',
	'robust',
	'scalable',
	'touchpoint',
	'value proposition',
	'stakeholder alignment',
	'operationalize',
	'granular insights',
	'bleeding-edge',
	'vertical integration',
	'hyper-personalized',
	'ecosystem',
	'future-proof',
	'data-driven',
	'actionable strategies',
	'low-hanging fruit',
	'mission alignment',
	'thought leadership',
	'innovative',
	'unprecedented',
	'embrace',
	'harness the power',
	'next-level',
	'ensure',
	'navigate',
	'best-in-class',
	'dive into',
	'disruptive',
	'emerge',
	'deep dive',
	'unleash',
	'ever-evolving',
	'unveil',
	'mission-critical',
	'unlock',
	'paradigm shift',
	'tailored',
	'utilize',
	'cutting-edge',
	'landscape',
	'underscore',
	'ever-changing',
	'diverse sources',
	'streamline',
	'holistic approach',
	'digital landscape',
	'supercharge',
	'intricate',
	'laser-focused',
	'conventional solutions',
	'bespoke',
	'orchestrating',
	'disruptive innovation',
	'manifests',
	'forge',
	'precision',
	'crafted',
	'vision',
	'alignment',
	'impact',
	'stakeholders',
	'metrics',
	'north star',
	'execution',
	'executing tasks',
	'row in the same direction',
	'lessons learned',
	'tapestry',
	'a testament to',
	'testament to',
	'boast',
	'showcase',
	'pivotal',
	'crucial',
	'commendable',
	'noteworthy',
	'versatile',
	'invaluable',
	'groundbreaking',
	'garner',
	'surpass',
	'advancement',
	'bolster',
	'foster',
	'elucidate',
	'encompass',
	'exacerbate',
	'illuminate',
	'culminate',
	'transformative',
	'pioneering',
	'multifaceted',
	'interplay',
	'comprehensive',
	'paramount',
	'resilience',
	'plethora',
	'myriad',
	'vibrant',
	'nestled',
	'renowned',
	'breathtaking',
	'hidden gem',
	'must-visit',
	'diverse array',
	'a wide range of',
	'a variety of',
	'valuable insights',
	'deeper understanding',
	'paving the way',
	'stands as',
	'serves as a',
	'plays a vital role',
	'plays a crucial role',
	'indelible mark',
	'setting the stage for',
	'continues to captivate',
	'rich heritage',
	'when it comes to',
	'enduring',
	'align with',
	'aligns with',
	'aligned with',
	'aligning with',
	'focal point',
	'deeply rooted',
	'key turning point',
	'reflects broader',
	'generated debate',
	'generated discussion',
	'active social media presence',
	'in the heart of',
	'natural beauty',
	'commitment to',
	'exemplify',
	'marks a',
	'represents a',
	'offers a glimpse'
];
